language: bash

os:
- linux

env:
  - BASHVER=
  - BASHVER=3.2
  - BASHVER=4.0
  - BASHVER=4.1
  - BASHVER=4.2
  - BASHVER=4.3
  - BASHVER=4.4
  - BASHVER=5

matrix:
  include:
    - os: osx

services:
  - docker

before_script:
 - |
   if [[ "${TRAVIS_OS_NAME:-}" == 'linux' ]]; then
     sudo apt-get install shellcheck
   fi

script:
- |
  if [[ "${TRAVIS_OS_NAME:-}" == 'linux' ]]; then
    ./shellcheck.sh
  fi

  if [[ "${TRAVIS_OS_NAME:-}" == 'linux' && -n "${BASHVER}" ]]; then
    docker build --build-arg bashver="${BASHVER}" --tag "bats/bats:bash-${BASHVER}" . &&
      docker run -it "bash:${BASHVER}" --version &&
      time docker run -it "bats/bats:bash-${BASHVER}" --tap /opt/bats/test
  else
    time bin/bats --formatter tap test
  fi

  if [[ "${TRAVIS_OS_NAME:-}" == 'linux' && "${BASHVER:-}" == 5 ]]; then
    docker run -it -v "${PWD}:/code" \
      quay.io/crio/crio-build-amd64-go1.14@sha256:d9e189369731b34514851ddf5e53cfaf0a829f7f22bc52d430bd34022862a710 \
      bash -c "/code/bin/bats /code/test"
  fi

notifications:
  email:
    on_success: never
